services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
    networks:
      - app-network

  tests:
    build:
      context: .
      dockerfile: ./ReservationManagementSystem.FunctionalTests/Dockerfile
    depends_on:
      - webapi
    environment:
      - BASE_ADDRESS=http://webapi:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
